### ISSUE TITLE
Latest Core Docker Compose Images Fail on Raspberry Pi

### ISSUE THREAD

**Issue by emielpopla** [DefGuard/deployment#30]
I wanted to deploy the Core container and the DB container on a Raspberry Pi 4 within my network but it fails with message:
'no matching manifest for linux/arm64/v8 in the manifest list entries'.

I found an image that works but it is already a month old: 15ff86984ebe5e89a419d5616d0c51b6a9309b04-aarch64

Is there a plan to support arm64 in the future so there is no need to set the image hash manually and have the latest updates?

**Comment by teon** [comment]
Hi @emielpopla - we had RPI builds, just disabled them since we didn't see much interest in that architecture.
We will enable them with next release then - which should be early next week.
I'll add it to our backlog so watch out for this issue / when closed there will be arm/rpi builds.
