### ISSUE TITLE
Insecure cookies not working

### ISSUE THREAD

**Issue by teon** [DefGuard/deployment#35]
on Firefox ‘ cookie « defguard_session »has been rejected because a non-https cookie can’t be set as « secure » ´. Chromium is less explicit but says : [GUARD] Not authorized to navigate
And .env sets DEFGUARD_COOKIE_INSECURE=true
Looks like the docker do not see ‘cookie insecure’

**Comment by wojcik91** [comment]
Fixed docker compose env variable config.
