### ISSUE TITLE
Setup script does not check if HTTP(S) ports are available before deploying

### ISSUE THREAD

**Issue by Freekers** [DefGuard/deployment#43]
On the very last step, the script stopped because port 80 was already occupied on my machine. Since I didn't know what the admin password was and where it's stored, I had no other choice than to delete the volumes folder and restart the script. A minor inconvenience, but it would be nice if the script would check up front if the required (non user changeable ports) are available prior to starting the script (similar as how it checks if the .volumes folder is already present)

**Comment by teon** [comment]
I think this is the person deploying responsibility. The script will just get bigger and overblown with all possible checks...
